(*********************************************************************************
 * Author:    	Daniel Castillo-Idrobo  
 * Created:   	October 24, 2025/10:43 AM 
 * Description: This task handles cap detection, not identification, at the entry
				point of the sorting station.
 *********************************************************************************)

PROGRAM _INIT
	(* Insert code here *)
	 
END_PROGRAM

PROGRAM _CYCLIC
	(* Insert code here *)
	 
END_PROGRAM

PROGRAM _EXIT
	(* Insert code here *)
	 
END_PROGRAM

